### ISSUE TITLE
Class okhttp3.HttpUrl not found when using Minio 8.6.0

### ISSUE THREAD

**Issue by rosario-vandebron** [minio/minio-java#1681]
Hello,
I am trying to use your great s3 compatible client to interact with our company s3 storage. 

I am using:
- Scala version: 2.13.16
- Java version 17.0.11
- sbt version 1.10.1

this is the code snippet that throw a compilation error:
```
private val s3Client = MinioClient
    .builder()
    .credentials(accessKey, secretKey)
    .region("nl-ams")
    .endpoint("https://s3.nl-ams.scw.cloud")
    .build()
```

this is the error:
```
Class okhttp3.HttpUrl not found - continuing with a stub.
[error]     .region("nl-ams")
[error]             ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

and this is the depenencies snippet of the build.sbt file
```
libraryDependencies ++= Seq(
  "com.amazonaws"               % "aws-java-sdk-s3"   % "1.12.788",
  "com.amazonaws"               % "aws-java-sdk-core" % "1.12.788",
  "io.minio" % "minio" % "8.6.0",
  "com.typesafe.scala-logging" %% "scala-logging"     % "3.9.5",
  "org.slf4j"                   % "slf4j-api"         % "2.0.17",
  "org.scalatest"              %% "scalatest"         % "3.2.19" % "test",
)
```

I've also tried to explicitly add okhttp but nothing change.

Note that everything works fine with minio version 8.17.0

Thanks for your help :)
